version: "3.8"

services:
    redis01:
        image: redis:3.2
        ports:
          - "6379:6379"
    redis02:
        image: redis:3.2
        ports:
          - "6380:6379"
    redis03:
        image: redis:3.2
        ports:
          - "6381:6379"
